[package]
name = "bzlib-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"

[build-dependencies]
bindgen = "0.65.1"
